// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: types/envelope.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type EnvelopeHeader struct {
	// 0位代表的是大小端
	//
	Flag                 int64    `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"`
	Length               int64    `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	Protocol             string   `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	SequenceId           string   `protobuf:"bytes,4,opt,name=sequenceId,proto3" json:"sequenceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnvelopeHeader) Reset()         { *m = EnvelopeHeader{} }
func (m *EnvelopeHeader) String() string { return proto.CompactTextString(m) }
func (*EnvelopeHeader) ProtoMessage()    {}
func (*EnvelopeHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_b14d620219b78278, []int{0}
}
func (m *EnvelopeHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnvelopeHeader.Unmarshal(m, b)
}
func (m *EnvelopeHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnvelopeHeader.Marshal(b, m, deterministic)
}
func (m *EnvelopeHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnvelopeHeader.Merge(m, src)
}
func (m *EnvelopeHeader) XXX_Size() int {
	return xxx_messageInfo_EnvelopeHeader.Size(m)
}
func (m *EnvelopeHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_EnvelopeHeader.DiscardUnknown(m)
}

var xxx_messageInfo_EnvelopeHeader proto.InternalMessageInfo

func (m *EnvelopeHeader) GetFlag() int64 {
	if m != nil {
		return m.Flag
	}
	return 0
}

func (m *EnvelopeHeader) GetLength() int64 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *EnvelopeHeader) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *EnvelopeHeader) GetSequenceId() string {
	if m != nil {
		return m.SequenceId
	}
	return ""
}

type Envelope struct {
	Header               *EnvelopeHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Payload              *Payload        `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Envelope) Reset()         { *m = Envelope{} }
func (m *Envelope) String() string { return proto.CompactTextString(m) }
func (*Envelope) ProtoMessage()    {}
func (*Envelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_b14d620219b78278, []int{1}
}
func (m *Envelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Envelope.Unmarshal(m, b)
}
func (m *Envelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Envelope.Marshal(b, m, deterministic)
}
func (m *Envelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Envelope.Merge(m, src)
}
func (m *Envelope) XXX_Size() int {
	return xxx_messageInfo_Envelope.Size(m)
}
func (m *Envelope) XXX_DiscardUnknown() {
	xxx_messageInfo_Envelope.DiscardUnknown(m)
}

var xxx_messageInfo_Envelope proto.InternalMessageInfo

func (m *Envelope) GetHeader() *EnvelopeHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Envelope) GetPayload() *Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

type Payload struct {
	Header               *Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Data                 []byte  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Payload) Reset()         { *m = Payload{} }
func (m *Payload) String() string { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()    {}
func (*Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_b14d620219b78278, []int{2}
}
func (m *Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload.Unmarshal(m, b)
}
func (m *Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload.Marshal(b, m, deterministic)
}
func (m *Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload.Merge(m, src)
}
func (m *Payload) XXX_Size() int {
	return xxx_messageInfo_Payload.Size(m)
}
func (m *Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_Payload proto.InternalMessageInfo

func (m *Payload) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Payload) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Header struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_b14d620219b78278, []int{3}
}
func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func init() {
	proto.RegisterType((*EnvelopeHeader)(nil), "common.EnvelopeHeader")
	proto.RegisterType((*Envelope)(nil), "common.Envelope")
	proto.RegisterType((*Payload)(nil), "common.Payload")
	proto.RegisterType((*Header)(nil), "common.Header")
}

func init() { proto.RegisterFile("types/envelope.proto", fileDescriptor_b14d620219b78278) }

var fileDescriptor_b14d620219b78278 = []byte{
	// 247 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x50, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x25, 0x36, 0x6c, 0xe3, 0xb4, 0x54, 0x18, 0x4a, 0x09, 0x1e, 0xa4, 0xe4, 0x50, 0xea, 0x65,
	0x85, 0xfa, 0x07, 0x85, 0x80, 0xde, 0xc2, 0xfe, 0xc1, 0xba, 0x19, 0xd3, 0xc3, 0x26, 0xbb, 0xa6,
	0x51, 0xec, 0xdf, 0x8b, 0x93, 0x5d, 0xb1, 0xb9, 0xcd, 0xbc, 0x37, 0xf3, 0xde, 0xe3, 0xc1, 0x7a,
	0xb8, 0x78, 0x3a, 0x3f, 0x51, 0xf7, 0x45, 0xd6, 0x79, 0x92, 0xbe, 0x77, 0x83, 0x43, 0x61, 0x5c,
	0xdb, 0xba, 0xae, 0xf8, 0x86, 0x55, 0x19, 0x98, 0x17, 0xd2, 0x35, 0xf5, 0x88, 0x90, 0xbe, 0x5b,
	0xdd, 0xe4, 0xc9, 0x36, 0xd9, 0xcf, 0x14, 0xcf, 0xb8, 0x01, 0x61, 0xa9, 0x6b, 0x86, 0x53, 0x7e,
	0xc3, 0x68, 0xd8, 0xf0, 0x1e, 0x32, 0x96, 0x33, 0xce, 0xe6, 0xb3, 0x6d, 0xb2, 0xbf, 0x55, 0x7f,
	0x3b, 0x3e, 0x00, 0x9c, 0xe9, 0xe3, 0x93, 0x3a, 0x43, 0xaf, 0x75, 0x9e, 0x32, 0xfb, 0x0f, 0x29,
	0x08, 0xb2, 0xe8, 0x8c, 0x12, 0xc4, 0x89, 0xdd, 0xd9, 0x75, 0x71, 0xd8, 0xc8, 0x31, 0x9e, 0xbc,
	0xce, 0xa6, 0xc2, 0x15, 0x3e, 0xc2, 0xdc, 0xeb, 0x8b, 0x75, 0xba, 0xe6, 0x40, 0x8b, 0xc3, 0x5d,
	0x7c, 0xa8, 0x46, 0x58, 0x45, 0xbe, 0x28, 0x61, 0x1e, 0x30, 0xdc, 0x4d, 0x5c, 0x56, 0xf1, 0x69,
	0xa2, 0x8e, 0x90, 0xd6, 0x7a, 0xd0, 0x2c, 0xbd, 0x54, 0x3c, 0x17, 0x19, 0x88, 0xf1, 0xea, 0xb8,
	0x83, 0xb5, 0x71, 0xad, 0x34, 0x64, 0xad, 0x6c, 0x7a, 0x6f, 0x82, 0xc8, 0x71, 0x59, 0x8e, 0x51,
	0xab, 0xdf, 0x02, 0xaa, 0xe4, 0x4d, 0x70, 0x13, 0xcf, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x21,
	0x16, 0x5e, 0x8a, 0x80, 0x01, 0x00, 0x00,
}
